### ISSUE TITLE
need support for provider credentials

### ISSUE THREAD

**Issue by sema4-dmytrobazulin** [arabold/serverless-export-env#15]
Looks like the plugin relies on stored provider credentials. Would be nice if those can be passed from command line params or taken from environment variables:

(Quick Setup section)
https://serverless.com/framework/docs/providers/aws/guide/credentials/

**Comment by gcampionpae** [comment]
I realize this issue is a bit over a year old but I ran across this issue as well when I was trying to run a CI job and was able to get around the issue by setting the credentials in serverless first `"serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile xxxxxxxx"`
